// Shared post list for blog.html and the homepage "From the Blog" strip.
// Add a new post here once and it appears in both places automatically.
// Order = display order (newest first).
const POSTS = [
  { href: 'posts/tuck-new-hampshire.html', category: 'Dramaturgy', show: 'Tuck Everlasting', title: "Angus Tuck's First Life: New Hampshire, 1763–1808", excerpt: "Angus Tuck has been alive since 1763. In this post, I build out the historical world behind the character: Colonial New Hampshire farm life, and the family's first decade keeping the secret.", homeExcerpt: "Angus Tuck has been alive since 1763. Building out the documented historical world behind the character, from colonial New Hampshire farm life to the family's first secret.", image: 'images/blog/Angus%20Tuck%20Character%20Journal/Mabry%20Mill.jpg', imageAlt: 'An old wooden gristmill with its water wheel turning above a still, reflecting millpond', date: 'Jul 2026' },
  { href: 'posts/tuck-immortality.html', category: 'Dramaturgy', show: 'Tuck Everlasting', title: "Angus Tuck's Next Life: The Cost of Immortality", excerpt: "What is Angus Tuck's long-term reaction to immortality? The physical mechanics of hidden survival, the psychological toll of endless waiting, and the theological frameworks that help make sense of a life with no ending.", homeExcerpt: "What is Angus Tuck's long-term reaction to immortality? The toll, the danger, and the theology that makes sense of it.", date: 'Jul 2026' },
  { href: 'posts/tuck-nine-questions.html', category: 'Character Work', show: 'Tuck Everlasting', title: "Building Angus Tuck: The Nine Questions", excerpt: "Uta Hagen asked for real specificity on every one of her Nine Questions, not one clean sentence each. A full run through all nine for Angus Tuck, informed by the historical and psychological research from the first two posts.", homeExcerpt: "Running Angus Tuck through Uta Hagen's Nine Questions, with the thoroughness she asked for.", date: 'Jul 2026' },
  { href: 'posts/daring-greatly.html',   category: 'Character Work', show: 'Vulnerability & Craft', title: "Daring Greatly on Stage: A Blueprint for Vulnerable Performance",   excerpt: "Technique and vulnerability are not opposing forces. Drawing on Brené Brown and Stanislavski, a framework for building the courage to risk emotional exposure and shed the armor we carry into the room.",   homeExcerpt: "A five-step framework for risking real emotional exposure on stage, built from Brené Brown's work on shame and vulnerability.", image: 'images/blog/Daring%20Greatly%20on%20Stage/Spring%20Awakening.jpg', imageAlt: 'Performer on stage at SOPAC', date: 'Jul 2026' },
  {
    href: 'posts/singing-actor.html',
    category: 'Character Work',
    show: 'Audition Technique',
    title: "Preparing “It’s Hard to Speak My Heart”: A Framework for the Singing Actor",
    excerpt: "Eye focus must be planned with the same rigor as breath management or vowel modification. A director’s approach to one audition piece.",
    homeExcerpt: "Breaking down one audition cut beat by beat, action verbs, physical gesture, and eye focus, built into a repeatable system.",
    image: 'images/blog/First-Day-of-Court.jpg',
    imageAlt: 'Leo Frank Trial, Fulton County Courtroom, Atlanta 1913',
    date: 'Apr 2026'
  },
  { href: 'posts/amelie-vulnerability.html',  category: 'Character Work', show: 'Amélie', title: 'Amélie: Navigating Neglect and Risking Vulnerability',   excerpt: "How Amélie’s character arc moves from the self-protective habits of childhood neglect toward the risk of genuine connection — and what that means for the actor and director.",   homeExcerpt: "How Amélie's arc moves from the self-protective habits of childhood neglect toward real connection, and what that asks of the actor.", date: 'Jul 2022' },
  { href: 'posts/amelie-scenic.html',          category: 'Dramaturgy',    show: 'Amélie', title: 'Amélie: Guimard, Art Nouveau, and the Scenic Aesthetic',   excerpt: "Hector Guimard’s Paris — its cast-iron entrances, riveted ornamentation, and democratic beauty — as the visual foundation for staging Amélie.",   homeExcerpt: "Hector Guimard's Paris — cast-iron entrances and Art Nouveau ornament — as the visual foundation for staging Amélie.", date: 'Apr 2022' },
  { href: 'posts/amelie-color.html',           category: 'Dramaturgy',    show: 'Amélie', title: "Amélie: La couleur de l'étrangeté",   excerpt: "Color in Jeunet's film is not atmospheric decoration — it's structural narrative. An analysis of how red, green, yellow, and blue carry emotional and dramatic weight.",   homeExcerpt: "How red, green, yellow, and blue work as structural narrative, not just atmosphere, in Jeunet's Amélie.", date: 'Mar 2022' },
  { href: 'posts/zaza-psychology.html',        category: 'Character Work', show: 'Zazà', title: 'Psychological Themes of Zazà',   excerpt: "Addiction, attachment, and the psychology of infidelity — the psychological architecture underlying Leoncavallo’s opera and what it asks of the performers who inhabit it.",   homeExcerpt: "Addiction, attachment, and trauma bonding: the psychological forces underlying Leoncavallo's opera.", date: 'Mar 2022' },
  { href: 'posts/zaza-visual.html',            category: 'Dramaturgy',    show: 'Zazà', title: 'The Visual Language of Zazà',    excerpt: 'Two pioneers of commercial art — Alphonse Mucha and J.C. Leyendecker — and how fin-de-siècle illustration shapes the visual world of this production.',   homeExcerpt: "Mucha and Leyendecker: how fin-de-siècle illustration shapes the visual world of this production.", date: 'Dec 2021' },
  { href: 'posts/zaza-leoncavallo.html',       category: 'Dramaturgy',    show: 'Zazà', title: 'Leoncavallo, Zazà & The Giovane Scuola',   excerpt: 'A biographical and historical introduction to Ruggiero Leoncavallo — the man behind Pagliacci, the rivalry with Puccini, and the opera that closed his most productive decade.',   date: 'Dec 2021' },
  { href: 'posts/mahagonny-medium.html',       category: 'Character Work', show: 'Mahagonny Songspiel & The Medium', title: 'Mahagonny & Medium: The Search for Meaning',   excerpt: 'Two operas, one directing season: how grief, belonging, and the courage to drop our armor connect Weill/Brecht and Menotti across seventy years.',   homeExcerpt: "How grief, belonging, and the courage to drop our armor connect Weill/Brecht and Menotti across seventy years.", date: 'Sep 2021' },
  { href: 'posts/medium-spiritualism.html',    category: 'Dramaturgy',    show: 'The Medium', title: 'The Medium: A History of Spiritualism',   excerpt: "The historical origins of American Spiritualism — and what Menotti’s opera illuminates about grief, belief, and the need to communicate beyond death.",   homeExcerpt: "The origins of American Spiritualism and what Menotti's opera illuminates about grief and belief.", date: 'Sep 2021' },
  { href: 'posts/mahagonny-concept.html',      category: 'Dramaturgy',    show: 'Mahagonny Songspiel', title: 'Mahagonny Songspiel — A Concept',   excerpt: "A production concept document for Kurt Weill and Bertolt Brecht’s Mahagonny Songspiel: nihilism, hedonism, grief, and the Weimar Berlin that made all of it possible.",   date: 'Aug 2021' },
];
